### ISSUE TITLE
armada ssh is no longer working with container ids

### ISSUE THREAD

**Issue by mmeinardi-ganymede** [armadaplatform/armada#116]
After upgrading to Armada 1.4.0 the command `armada ssh` no longer accepts short form of container ids. E.g.:

    vagrant@ubuntu-14:/projects/gumball-finder$ armada list
    Name            Address              ID            Status   Tags
    armada          192.168.2.116:8900   349cb2f73ea2  passing  -
    gumball-finder  192.168.2.116:4999   9a01dc151544  passing  -

    vagrant@ubuntu-14:/projects/gumball-finder$ armada ssh 9a0
    Command failed: IndexError - list index out of range

    vagrant@ubuntu-14:/projects/gumball-finder$ armada ssh gumball-finder
    Connecting to obiady.gd...
    root@9a01dc151544:/#

**Comment by karamazi** [comment]
Reverting back to using `get_matched_containers` method  instead of `/list` API endpoint resolves the problem. However, we lose 'free' status information. 

https://github.com/armadaplatform/armada/pull/118
