### ISSUE TITLE
Improve `armada build --squash`

### ISSUE THREAD

**Issue by fwojciak** [armadaplatform/armada#122]
Currently, an image squashed with `armada build --squash` consists of only one layer, which prevents `docker pull/push/build` commands from reusing shared layers between images.

Perhaps, after building an image, we should only squash the layers introduced by the service, i.e. squash only layers after: `FROM base_image` in Dockerfile. We would still have a lot less layers than without squashing, and retain docker cache reusing.

**Comment by krise3k** [comment]
For fixing it we can use https://github.com/docker/docker/pull/22641

**Comment by fwojciak** [comment]
#165
