### ISSUE TITLE
No module named 'armada_command'

### ISSUE THREAD

**Issue by ryneeverett** [armadaplatform/armada#23]
How is armada supposed to get in /opt? Shouldn't there be something like `git clone https://github.com/armadaplatform/armada.git /opt/armada` somewhere in `install.sh`?

```sh
$ bash <(curl -sL http://armada.sh/install)
...
$ armada --help
/usr/bin/python: Error while finding spec for 'armada_command.armada' (<class 'ImportError'>: No module named 'armada_command')
```

**Comment by karamazi** [comment]
Hey there,
`/opt/armada` is copied out from armada's container through this line:
https://github.com/armadaplatform/armada-website/blob/master/source/install/armada-runner#L134

Could you tell me what OS are you using, and did you get any errors during installation?

**Comment by ryneeverett** [comment]
Thanks @karamazi, that was enough to get it working. I opened armadaplatform/armada-website/pull/9 and armadaplatform/armada-website/pull/10 to address the issues.

**Comment by ryneeverett** [comment]
Well I spoke too soon. That was enough to get the container at least starting, but I still haven't gotten the command working.

```sh
$ armada --help
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/armada/armada_command/armada.py", line 6, in <module>
    import armada_api
ImportError: No module named 'armada_api'
```

I take it `/opt/armada/armada_command` is supposed to be added to the `PYTHONPATH` somewhere?

**Comment by fwojciak** [comment]
It seems like python3 is your default python, and armada CLI uses python2.
Quick fix should be to edit file `/usr/local/bin/armada` on your host and change line:
`python -m armada_command.armada $@`
to:
`python2 -m armada_command.armada $@`

Pull request https://github.com/armadaplatform/armada-website/pull/11/files

**Comment by ryneeverett** [comment]
Thanks @fwojciak, that was indeed another issue. I opened armadaplatform/armada-website/pull/12 against the python2 branch to make sure requests gets installed into the correct python.

**Comment by ryneeverett** [comment]
Well the combination of all these changes has given me a working `armada` command, but the container is throwing an error.

```sh
$ sudo armada-runner restart
Stopping armada...
Starting armada...
conntrack v1.4.3 (conntrack-tools): connection tracking table has been emptied.
Waiting for armada running state...
Waiting for armada running state timed out :(

$ armada info
Ship name      Ship role  API address    API status  Version
192.168.1.143  leader     192.168.1.143  -           error  

ERROR: There is no active leader. Armada is not working!
```

**Comment by karamazi** [comment]
This may be related to change in Docker interface IP address. What's your Docker version?

**Comment by ryneeverett** [comment]
```sh
$ docker --version
Docker version 1.9.1, build a34a1d5-dirty
```

**Comment by karamazi** [comment]
A'ight, this is definitely related to a Docker version.  Armada uses static Docker IP which apparently has changed sometime after 1.8 version. We'll try to fix it the first thing tomorrow morning :)

**Comment by karamazi** [comment]
Pull request: #24.

**Comment by karamazi** [comment]
Thanks for your feedback!  We've released fixed version, you can update it with installation script :)
Out of curiosity, could you tell me how did you come by Armada?

**Comment by ryneeverett** [comment]
Seems to be working now. Thanks for addressing this so quickly.

I'm really not sure how I came by armada, I've been actively searching for a lightweight tool to deploy docker containers for a while now and I'm hoping this is it.

One additional piece of feedback: given the current speed of your shipyard it would probably be faster to build locally than to pull images.
